spring.application.name=automation-engine
server.servlet.context-path=/project
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework=INFO


#spring.datasource.url=jdbc:mysql://localhost:3306/project_database
#spring.datasource.username=root
#spring.datasource.password=tiger
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Set the root logging level to WARN, only showing warnings and errors by default
logging.level.root=WARN

# Set the logging level for a specific application package to DEBUG for detailed debugging
#logging.level.com.example.myapp=DEBUG

# Enable debug logging for Spring web components
logging.level.org.springframework.web=DEBUG

# Configure logs to be written to a file named 'myapp.log' in the current directory
logging.file.name=myapp.log

# Customize the console log pattern to be more concise
logging.pattern.console=%d{HH:mm} %-5level %logger{36} - %msg%n

